/**
 * DNA File Validation Utilities
 * 
 * Provides comprehensive validation for genetic data files including:
 * - File format detection (23andMe, AncestryDNA, FTDNA, etc.)
 * - Compression format handling (GZIP, ZIP)
 * - Content validation (SNP count, format checks)
 * - Decompression utilities
 */

export type DnaFileFormat = '23andme' | 'ancestry' | 'ftdna' | 'myheritage' | 'livingdna' | 'generic' | 'unknown';
export type CompressionFormat = 'none' | 'gzip' | 'zip';

export interface DnaFileValidation {
  isValid: boolean;
  format: DnaFileFormat;
  compression: CompressionFormat;
  estimatedSnpCount: number;
  errors: string[];
  warnings: string[];
}

export interface DnaFileInfo {
  name: string;
  size: number;
  format: DnaFileFormat;
  compression: CompressionFormat;
  isValid: boolean;
}

// File extension to format mapping
const FORMAT_EXTENSIONS: Record<string, DnaFileFormat> = {
  '.23andme.txt': '23andme',
  '.23andme': '23andme',
  '.ancestry.txt': 'ancestry',
  '.ancestrydna.txt': 'ancestry',
  '.ftdna.txt': 'ftdna',
  '.familyfinder.txt': 'ftdna',
  '.myheritage.txt': 'myheritage',
  '.livingdna.txt': 'livingdna',
};

// Format detection headers
const FORMAT_HEADERS: Record<DnaFileFormat, string[]> = {
  '23andme': ['# This data file generated by 23andMe', 'RSID', 'CHROMOSOME', 'POSITION', 'GENOTYPE'],
  'ancestry': ['#AncestryDNA', 'rsid', 'chromosome', 'position', 'allele1', 'allele2'],
  'ftdna': ['RSID,CHROMOSOME,POSITION,RESULT', 'RSID\tCHROMOSOME\tPOSITION\tRESULT'],
  'myheritage': ['RSID,CHROMOSOME,POSITION,RESULT', '# MyHeritage DNA'],
  'livingdna': ['# Living DNA', 'rsid', 'chromosome', 'position', 'allele'],
  'generic': [],
  'unknown': [],
};

/**
 * Detect compression format from filename
 */
export function detectCompression(filename: string): CompressionFormat {
  const lowerName = filename.toLowerCase();
  if (lowerName.endsWith('.gz') || lowerName.endsWith('.gzip')) {
    return 'gzip';
  }
  if (lowerName.endsWith('.zip')) {
    return 'zip';
  }
  return 'none';
}

/**
 * Detect DNA file format from filename and content
 */
export function detectDnaFormat(filename: string, sampleContent?: string): DnaFileFormat {
  const lowerName = filename.toLowerCase();
  
  // Check filename patterns first
  for (const [ext, format] of Object.entries(FORMAT_EXTENSIONS)) {
    if (lowerName.includes(ext)) {
      return format;
    }
  }
  
  // Check content if provided
  if (sampleContent) {
    const firstLines = sampleContent.split('\n').slice(0, 20).join('\n').toLowerCase();
    
    if (firstLines.includes('23andme') || firstLines.includes('rsid\tchromosome\tposition\tgenotype')) {
      return '23andme';
    }
    if (firstLines.includes('ancestrydna') || firstLines.includes('ancestry.com')) {
      return 'ancestry';
    }
    if (firstLines.includes('family tree dna') || firstLines.includes('ftdna')) {
      return 'ftdna';
    }
    if (firstLines.includes('myheritage')) {
      return 'myheritage';
    }
    if (firstLines.includes('living dna')) {
      return 'livingdna';
    }
    
    // Generic SNP file detection
    if (firstLines.includes('rsid') || firstLines.includes('rs#') || firstLines.includes('snp')) {
      return 'generic';
    }
  }
  
  return 'unknown';
}

/**
 * Validate file size
 */
export function validateFileSize(size: number, maxSizeMB: number = 100): { valid: boolean; error?: string } {
  const maxBytes = maxSizeMB * 1024 * 1024;
  if (size > maxBytes) {
    return { 
      valid: false, 
      error: `File size (${(size / 1024 / 1024).toFixed(1)}MB) exceeds maximum allowed (${maxSizeMB}MB)` 
    };
  }
  if (size === 0) {
    return { valid: false, error: 'File is empty' };
  }
  return { valid: true };
}

/**
 * Validate file extension
 */
export function validateFileExtension(filename: string): { valid: boolean; error?: string } {
  const validExtensions = ['.txt', '.csv', '.tsv', '.gz', '.gzip', '.zip'];
  const lowerName = filename.toLowerCase();
  
  const hasValidExtension = validExtensions.some(ext => lowerName.endsWith(ext));
  
  if (!hasValidExtension) {
    return { 
      valid: false, 
      error: 'Invalid file format. Please upload .txt, .csv, .tsv, .gz, or .zip files' 
    };
  }
  
  return { valid: true };
}

/**
 * Estimate SNP count from file size and compression
 */
export function estimateSnpCount(fileSize: number, compression: CompressionFormat): number {
  // Rough estimates based on average bytes per SNP
  const bytesPerSnp = 20; // Average for uncompressed text format
  
  let compressionRatio = 1;
  switch (compression) {
    case 'gzip':
      compressionRatio = 5; // GZIP typically 5:1 for text
      break;
    case 'zip':
      compressionRatio = 4; // ZIP typically 4:1 for text
      break;
    default:
      compressionRatio = 1;
  }
  
  const estimatedUncompressedSize = fileSize * compressionRatio;
  return Math.floor(estimatedUncompressedSize / bytesPerSnp);
}

/**
 * Validate DNA file header/content
 */
export async function validateDnaContent(
  file: File, 
  sampleSize: number = 1024 * 10
): Promise<{ valid: boolean; format: DnaFileFormat; errors: string[]; warnings: string[] }> {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  try {
    // Read first chunk of file
    const sampleChunk = file.slice(0, sampleSize);
    const content = await sampleChunk.text();
    
    const format = detectDnaFormat(file.name, content);
    
    if (format === 'unknown') {
      warnings.push('Could not automatically detect file format. Will attempt generic parsing.');
    }
    
    // Check for required columns/fields
    const lines = content.split('\n').slice(0, 50);
    const headerLines = lines.filter(l => !l.startsWith('#') && l.trim());
    
    if (headerLines.length === 0) {
      errors.push('File appears to be empty or has no valid data rows');
    } else {
      const firstDataLine = headerLines[0].toLowerCase();
      
      // Check for common SNP identifiers
      const hasRsid = firstDataLine.includes('rs') || content.includes('rsid');
      const hasPosition = firstDataLine.includes('position') || firstDataLine.includes('pos');
      const hasChromosome = firstDataLine.includes('chromosome') || firstDataLine.includes('chr');
      
      if (!hasRsid && !hasPosition) {
        warnings.push('File may not contain standard SNP data (rsID or position fields not detected)');
      }
      
      // Check for binary/corrupted data
      const nullByteCount = (content.match(/\0/g) || []).length;
      if (nullByteCount > 10) {
        errors.push('File appears to be binary or corrupted. Please upload a valid text file.');
      }
    }
    
    return {
      valid: errors.length === 0,
      format,
      errors,
      warnings,
    };
  } catch (error) {
    return {
      valid: false,
      format: 'unknown',
      errors: ['Failed to read file: ' + (error as Error).message],
      warnings: [],
    };
  }
}

/**
 * Comprehensive DNA file validation
 */
export async function validateDnaFile(file: File): Promise<DnaFileValidation> {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  // Validate extension
  const extValidation = validateFileExtension(file.name);
  if (!extValidation.valid) {
    errors.push(extValidation.error!);
  }
  
  // Validate size
  const sizeValidation = validateFileSize(file.size);
  if (!sizeValidation.valid) {
    errors.push(sizeValidation.error!);
  }
  
  // Detect compression
  const compression = detectCompression(file.name);
  
  // If file is compressed, we can't fully validate content without decompressing
  // But we can do basic checks
  if (compression !== 'none') {
    // Check for reasonable compressed size (at least 1KB for a valid DNA file)
    if (file.size < 1024) {
      errors.push('Compressed file is too small to contain valid DNA data');
    }
    
    const estimatedSnps = estimateSnpCount(file.size, compression);
    
    if (estimatedSnps < 10000) {
      warnings.push(`File appears to contain fewer than 10,000 SNPs. Most DNA tests include 600,000+ SNPs.`);
    }
    
    return {
      isValid: errors.length === 0,
      format: detectDnaFormat(file.name),
      compression,
      estimatedSnpCount: estimatedSnps,
      errors,
      warnings: [...warnings, 'File is compressed. Full validation will occur during processing.'],
    };
  }
  
  // For uncompressed files, do full content validation
  const contentValidation = await validateDnaContent(file);
  
  return {
    isValid: errors.length === 0 && contentValidation.valid,
    format: contentValidation.format,
    compression,
    estimatedSnpCount: estimateSnpCount(file.size, compression),
    errors: [...errors, ...contentValidation.errors],
    warnings: [...warnings, ...contentValidation.warnings],
  };
}

/**
 * Get human-readable format name
 */
export function getFormatDisplayName(format: DnaFileFormat): string {
  const names: Record<DnaFileFormat, string> = {
    '23andme': '23andMe',
    'ancestry': 'AncestryDNA',
    'ftdna': 'Family Tree DNA',
    'myheritage': 'MyHeritage DNA',
    'livingdna': 'Living DNA',
    'generic': 'Generic SNP File',
    'unknown': 'Unknown Format',
  };
  return names[format] || 'Unknown';
}

/**
 * Get compression display name
 */
export function getCompressionDisplayName(compression: CompressionFormat): string {
  const names: Record<CompressionFormat, string> = {
    'none': 'Uncompressed',
    'gzip': 'GZIP Compressed',
    'zip': 'ZIP Compressed',
  };
  return names[compression];
}

/**
 * Check if file needs decompression
 */
export function needsDecompression(compression: CompressionFormat): boolean {
  return compression !== 'none';
}

/**
 * Get file type icon info
 */
export function getFileTypeInfo(filename: string): { 
  icon: 'text' | 'archive' | 'compressed'; 
  color: string; 
  label: string;
} {
  const compression = detectCompression(filename);
  const format = detectDnaFormat(filename);
  
  if (compression === 'gzip') {
    return { icon: 'compressed', color: 'purple', label: 'GZIP' };
  }
  if (compression === 'zip') {
    return { icon: 'archive', color: 'blue', label: 'ZIP' };
  }
  
  return { icon: 'text', color: 'indigo', label: getFormatDisplayName(format) };
}
