import { describe, it, expect } from 'vitest';
import {
  detectCompression,
  detectDnaFormat,
  validateFileSize,
  validateFileExtension,
  estimateSnpCount,
  getFormatDisplayName,
  getCompressionDisplayName,
  getFileTypeInfo,
  needsDecompression,
} from './dna-validation';

describe('dnaValidation', () => {
  describe('detectCompression', () => {
    it('detects gzip compression', () => {
      expect(detectCompression('genome.txt.gz')).toBe('gzip');
      expect(detectCompression('genome.gzip')).toBe('gzip');
    });

    it('detects zip compression', () => {
      expect(detectCompression('genome.zip')).toBe('zip');
      expect(detectCompression('genome.ZIP')).toBe('zip');
    });

    it('detects no compression', () => {
      expect(detectCompression('genome.txt')).toBe('none');
      expect(detectCompression('genome.csv')).toBe('none');
    });
  });

  describe('detectDnaFormat', () => {
    it('detects 23andMe format from filename', () => {
      expect(detectDnaFormat('genome.23andme.txt')).toBe('23andme');
      expect(detectDnaFormat('genome.23andme')).toBe('23andme');
    });

    it('detects AncestryDNA format from filename', () => {
      expect(detectDnaFormat('genome.ancestry.txt')).toBe('ancestry');
      expect(detectDnaFormat('genome.ancestrydna.txt')).toBe('ancestry');
    });

    it('detects 23andMe format from content', () => {
      const content = '# This data file generated by 23andMe\nRSID\tCHROMOSOME\tPOSITION\tGENOTYPE';
      expect(detectDnaFormat('unknown.txt', content)).toBe('23andme');
    });

    it('detects AncestryDNA format from content', () => {
      const content = '#AncestryDNA\nrsid\tchromosome\tposition\tallele1\tallele2';
      expect(detectDnaFormat('unknown.txt', content)).toBe('ancestry');
    });

    it('detects generic SNP format', () => {
      const content = 'rsid,chromosome,position,genotype\nrs123,1,12345,AT';
      expect(detectDnaFormat('unknown.txt', content)).toBe('generic');
    });

    it('returns unknown for unrecognized format', () => {
      expect(detectDnaFormat('random.txt')).toBe('unknown');
      expect(detectDnaFormat('unknown.bin')).toBe('unknown');
    });
  });

  describe('validateFileSize', () => {
    it('validates files under max size', () => {
      const result = validateFileSize(1024 * 1024, 100); // 1MB < 100MB
      expect(result.valid).toBe(true);
      expect(result.error).toBeUndefined();
    });

    it('rejects files over max size', () => {
      const result = validateFileSize(200 * 1024 * 1024, 100); // 200MB > 100MB
      expect(result.valid).toBe(false);
      expect(result.error).toContain('exceeds maximum');
    });

    it('rejects empty files', () => {
      const result = validateFileSize(0, 100);
      expect(result.valid).toBe(false);
      expect(result.error).toBe('File is empty');
    });
  });

  describe('validateFileExtension', () => {
    it('validates txt extension', () => {
      expect(validateFileExtension('genome.txt').valid).toBe(true);
    });

    it('validates csv extension', () => {
      expect(validateFileExtension('genome.csv').valid).toBe(true);
    });

    it('validates gz extension', () => {
      expect(validateFileExtension('genome.txt.gz').valid).toBe(true);
    });

    it('validates zip extension', () => {
      expect(validateFileExtension('genome.zip').valid).toBe(true);
    });

    it('rejects invalid extensions', () => {
      expect(validateFileExtension('genome.pdf').valid).toBe(false);
      expect(validateFileExtension('genome.jpg').valid).toBe(false);
      expect(validateFileExtension('genome.exe').valid).toBe(false);
    });
  });

  describe('estimateSnpCount', () => {
    it('estimates SNPs for uncompressed file', () => {
      const result = estimateSnpCount(1000000, 'none'); // 1MB
      expect(result).toBeGreaterThan(0);
    });

    it('estimates more SNPs for gzip compressed file', () => {
      const compressed = estimateSnpCount(1000000, 'gzip');
      const uncompressed = estimateSnpCount(1000000, 'none');
      expect(compressed).toBeGreaterThan(uncompressed);
    });

    it('estimates more SNPs for zip compressed file', () => {
      const compressed = estimateSnpCount(1000000, 'zip');
      const uncompressed = estimateSnpCount(1000000, 'none');
      expect(compressed).toBeGreaterThan(uncompressed);
    });
  });

  describe('getFormatDisplayName', () => {
    it('returns correct display names', () => {
      expect(getFormatDisplayName('23andme')).toBe('23andMe');
      expect(getFormatDisplayName('ancestry')).toBe('AncestryDNA');
      expect(getFormatDisplayName('ftdna')).toBe('Family Tree DNA');
      expect(getFormatDisplayName('myheritage')).toBe('MyHeritage DNA');
      expect(getFormatDisplayName('livingdna')).toBe('Living DNA');
      expect(getFormatDisplayName('generic')).toBe('Generic SNP File');
      expect(getFormatDisplayName('unknown')).toBe('Unknown Format');
    });
  });

  describe('getCompressionDisplayName', () => {
    it('returns correct compression names', () => {
      expect(getCompressionDisplayName('none')).toBe('Uncompressed');
      expect(getCompressionDisplayName('gzip')).toBe('GZIP Compressed');
      expect(getCompressionDisplayName('zip')).toBe('ZIP Compressed');
    });
  });

  describe('needsDecompression', () => {
    it('returns true for compressed files', () => {
      expect(needsDecompression('gzip')).toBe(true);
      expect(needsDecompression('zip')).toBe(true);
    });

    it('returns false for uncompressed files', () => {
      expect(needsDecompression('none')).toBe(false);
    });
  });

  describe('getFileTypeInfo', () => {
    it('returns compressed info for gzip files', () => {
      const info = getFileTypeInfo('genome.txt.gz');
      expect(info.icon).toBe('compressed');
      expect(info.color).toBe('purple');
      expect(info.label).toBe('GZIP');
    });

    it('returns archive info for zip files', () => {
      const info = getFileTypeInfo('genome.zip');
      expect(info.icon).toBe('archive');
      expect(info.color).toBe('blue');
      expect(info.label).toBe('ZIP');
    });

    it('returns text info for txt files', () => {
      const info = getFileTypeInfo('genome.txt');
      expect(info.icon).toBe('text');
      expect(info.color).toBe('indigo');
    });
  });
});
