import { describe, it, expect } from 'vitest';
import {
  parseGeneticData,
  getSNPsByRegion,
  findSNP,
  getSNPsWithGenotype,
  validateGenomeData,
  getGenomeStats,
  detectSource,
} from './parser';
import type { SNP } from '~/types/genetics';

// Test data generators
const generate23andMeData = (snps: Partial<SNP>[] = []): string => {
  const header = '# This data file generated by 23andMe v5.0\n#\n# rsid\tchromosome\tposition\tgenotype\n';
  const defaultSNPs: Partial<SNP>[] = [
    { rsid: 'rs1801133', chromosome: '1', position: 11856378, genotype: 'GG' },
    { rsid: 'rs662', chromosome: '1', position: 230845699, genotype: 'AG' },
    { rsid: 'rs1799983', chromosome: '7', position: 150696111, genotype: 'TT' },
    { rsid: 'rs429358', chromosome: '19', position: 45411941, genotype: 'CT' },
  ];
  const allSNPs = [...defaultSNPs, ...snps];
  const lines = allSNPs.map(snp => 
    `${snp.rsid}\t${snp.chromosome}\t${snp.position}\t${snp.genotype}`
  ).join('\n');
  return header + lines;
};

const generateAncestryDNAData = (snps: Partial<SNP>[] = []): string => {
  const header = '#AncestryDNA raw data download\n#\n# rsid,chromosome,position,allele1,allele2\n';
  const defaultSNPs: Partial<SNP>[] = [
    { rsid: 'rs1801133', chromosome: '1', position: 11856378, genotype: 'GG' },
    { rsid: 'rs662', chromosome: '1', position: 230845699, genotype: 'AG' },
    { rsid: 'rs1799983', chromosome: '7', position: 150696111, genotype: 'TT' },
    { rsid: 'rs429358', chromosome: '19', position: 45411941, genotype: 'CT' },
  ];
  const allSNPs = [...defaultSNPs, ...snps];
  const lines = allSNPs.map(snp => {
    const allele1 = snp.genotype?.charAt(0) || '-';
    const allele2 = snp.genotype?.charAt(1) || '-';
    return `${snp.rsid},${snp.chromosome},${snp.position},${allele1},${allele2}`;
  }).join('\n');
  return header + lines;
};

const generateMyHeritageData = (snps: Partial<SNP>[] = []): string => {
  const header = '# MyHeritage DNA raw data\n# Format: rsid, chromosome, position, genotype\n';
  const defaultSNPs: Partial<SNP>[] = [
    { rsid: 'rs1801133', chromosome: '1', position: 11856378, genotype: 'GG' },
    { rsid: 'rs662', chromosome: '1', position: 230845699, genotype: 'AG' },
  ];
  const allSNPs = [...defaultSNPs, ...snps];
  const lines = allSNPs.map(snp => 
    `${snp.rsid}\t${snp.chromosome}\t${snp.position}\t${snp.genotype}`
  ).join('\n');
  return header + lines;
};

const generateLargeSNPSet = (count: number): Partial<SNP>[] => {
  const snps: Partial<SNP>[] = [];
  for (let i = 0; i < count; i++) {
    snps.push({
      rsid: `rs${1000000 + i}`,
      chromosome: String((i % 22) + 1),
      position: 1000000 + (i * 100),
      genotype: ['AA', 'AC', 'AG', 'AT', 'CC', 'CG', 'CT', 'GG', 'GT', 'TT'][i % 10],
    });
  }
  return snps;
};

describe('Genome Parser', () => {
  describe('parseGeneticData', () => {
    it('parses valid 23andMe format data', () => {
      const content = generate23andMeData();
      const result = parseGeneticData(content);

      expect(result.source).toBe('23andme');
      expect(result.snps).toHaveLength(4);
      expect(result.validSnps).toBe(4);
      expect(result.totalLines).toBeGreaterThan(0);

      // Check first SNP
      expect(result.snps[0]).toEqual({
        rsid: 'rs1801133',
        chromosome: '1',
        position: 11856378,
        genotype: 'GG',
      });
    });

    it('parses valid AncestryDNA format data', () => {
      const content = generateAncestryDNAData();
      const result = parseGeneticData(content);

      expect(result.source).toBe('ancestry');
      expect(result.snps).toHaveLength(4);
      expect(result.validSnps).toBe(4);

      // Check that genotype is properly combined from alleles
      expect(result.snps[0].genotype).toBe('GG');
      expect(result.snps[1].genotype).toBe('AG');
    });

    it('parses MyHeritage format data (similar to 23andMe)', () => {
      const content = generateMyHeritageData();
      const result = parseGeneticData(content);

      expect(result.source).toBe('myheritage');
      expect(result.snps).toHaveLength(2);
      expect(result.validSnps).toBe(2);

      expect(result.snps[0]).toEqual({
        rsid: 'rs1801133',
        chromosome: '1',
        position: 11856378,
        genotype: 'GG',
      });
    });

    it('auto-detects 23andMe format without header', () => {
      const lines = [
        'rs1801133\t1\t11856378\tGG',
        'rs662\t1\t230845699\tAG',
        'rs1799983\t7\t150696111\tTT',
      ].join('\n');
      const result = parseGeneticData(lines);

      expect(result.source).toBe('23andme');
      expect(result.snps).toHaveLength(3);
    });

    it('auto-detects AncestryDNA format without header', () => {
      const lines = [
        'rs1801133,1,11856378,G,G',
        'rs662,1,230845699,A,G',
        'rs1799983,7,150696111,T,T',
      ].join('\n');
      const result = parseGeneticData(lines);

      expect(result.source).toBe('ancestry');
      expect(result.snps).toHaveLength(3);
    });

    it('handles empty content', () => {
      const result = parseGeneticData('');

      expect(result.snps).toHaveLength(0);
      expect(result.validSnps).toBe(0);
      expect(result.source).toBe('other');
    });

    it('handles whitespace-only content', () => {
      const result = parseGeneticData('   \n\n   \n');

      expect(result.snps).toHaveLength(0);
      expect(result.validSnps).toBe(0);
    });

    it('handles content with only comments', () => {
      const content = '# This is a comment\n# Another comment\n';
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(0);
      expect(result.validSnps).toBe(0);
    });

    it('ignores malformed lines', () => {
      const content = [
        '# Comment line',
        'rsid\tchromosome\tposition\tgenotype',
        'rs1801133\t1\t11856378\tGG',
        'malformed line without tabs',
        'rs662\t1\t230845699\tAG',
        'notEnoughFields\t1',
        '',
      ].join('\n');
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(2);
    });

    it('ignores lines without rsid prefix', () => {
      const content = [
        'i12345\t1\t11856378\tGG',
        'rs1801133\t1\t11856378\tGG',
        'd78901\t1\t11856379\tAA',
      ].join('\n');
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(1);
      expect(result.snps[0].rsid).toBe('rs1801133');
    });

    it('handles X, Y, and MT chromosomes', () => {
      const content = [
        'rs1234567\tX\t123456\tGG',
        'rs2345678\tY\t234567\tCT',
        'rs3456789\tMT\t345678\tAA',
      ].join('\n');
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(3);
      expect(result.snps[0].chromosome).toBe('X');
      expect(result.snps[1].chromosome).toBe('Y');
      expect(result.snps[2].chromosome).toBe('MT');
    });

    it('sorts SNPs by chromosome and position', () => {
      const content = [
        'rs3\t2\t300\tGG',
        'rs1\t1\t100\tAA',
        'rs4\t2\t100\tCC',
        'rs2\t1\t200\tTT',
      ].join('\n');
      const result = parseGeneticData(content);

      expect(result.snps[0].rsid).toBe('rs1');
      expect(result.snps[1].rsid).toBe('rs2');
      expect(result.snps[2].rsid).toBe('rs4');
      expect(result.snps[3].rsid).toBe('rs3');
    });

    it('handles AncestryDNA with dashes in alleles', () => {
      const content = [
        'rs1234567,1,11856378,-,-',
        'rs1801133,1,11856379,G,G',
      ].join('\n');
      const result = parseGeneticData(content);

      expect(result.snps[0].genotype).toBe('');
      expect(result.snps[1].genotype).toBe('GG');
    });
  });

  describe('detectSource', () => {
    it('detects 23andMe by header text', () => {
      const content = '# This data file generated by 23andMe v5.0\nrs123\t1\t100\tAA';
      expect(detectSource(content)).toBe('23andme');
    });

    it('detects 23andMe by column headers', () => {
      const content = 'rsid\tchromosome\tposition\tgenotype\nrs123\t1\t100\tAA';
      expect(detectSource(content)).toBe('23andme');
    });

    it('detects AncestryDNA by header text', () => {
      const content = '#AncestryDNA raw data download\nrs123,1,100,A,A';
      expect(detectSource(content)).toBe('ancestry');
    });

    it('detects AncestryDNA by column headers', () => {
      const content = 'rsid,chromosome,position,allele1,allele2\nrs123,1,100,A,A';
      expect(detectSource(content)).toBe('ancestry');
    });

    it('detects MyHeritage by header text', () => {
      const content = '# MyHeritage DNA raw data\nrs123\t1\t100\tAA';
      expect(detectSource(content)).toBe('myheritage');
    });

    it('detects format by delimiter when no header', () => {
      expect(detectSource('rs123\t1\t100\tAA')).toBe('23andme');
      expect(detectSource('rs123,1,100,A,A')).toBe('ancestry');
    });

    it('returns other for unknown format', () => {
      expect(detectSource('some random content')).toBe('other');
      expect(detectSource('')).toBe('other');
    });
  });

  describe('getSNPsByRegion', () => {
    const snps: SNP[] = [
      { rsid: 'rs1', chromosome: '1', position: 1000, genotype: 'AA' },
      { rsid: 'rs2', chromosome: '1', position: 2000, genotype: 'GG' },
      { rsid: 'rs3', chromosome: '1', position: 3000, genotype: 'CC' },
      { rsid: 'rs4', chromosome: '2', position: 1000, genotype: 'TT' },
      { rsid: 'rs5', chromosome: '1', position: 2500, genotype: 'AT' },
    ];

    it('filters SNPs by region', () => {
      const result = getSNPsByRegion(snps, '1', 1500, 3500);

      expect(result).toHaveLength(3);
      expect(result.map(s => s.rsid)).toEqual(['rs2', 'rs3', 'rs5']);
    });

    it('returns empty array when no SNPs in region', () => {
      const result = getSNPsByRegion(snps, '1', 5000, 6000);

      expect(result).toHaveLength(0);
    });

    it('returns empty array for different chromosome', () => {
      const result = getSNPsByRegion(snps, '3', 0, 10000);

      expect(result).toHaveLength(0);
    });

    it('includes SNPs at boundary positions', () => {
      const result = getSNPsByRegion(snps, '1', 2000, 2500);

      expect(result).toHaveLength(2);
      expect(result.map(s => s.rsid)).toEqual(['rs2', 'rs5']);
    });

    it('returns empty array for empty input', () => {
      expect(getSNPsByRegion([], '1', 0, 1000)).toHaveLength(0);
    });
  });

  describe('findSNP', () => {
    const snps: SNP[] = [
      { rsid: 'rs1801133', chromosome: '1', position: 11856378, genotype: 'GG' },
      { rsid: 'rs662', chromosome: '1', position: 230845699, genotype: 'AG' },
      { rsid: 'rs1799983', chromosome: '7', position: 150696111, genotype: 'TT' },
    ];

    it('finds SNP by rsid', () => {
      const result = findSNP(snps, 'rs662');

      expect(result).toBeDefined();
      expect(result?.rsid).toBe('rs662');
      expect(result?.chromosome).toBe('1');
      expect(result?.position).toBe(230845699);
    });

    it('is case-insensitive', () => {
      const result = findSNP(snps, 'RS662');

      expect(result).toBeDefined();
      expect(result?.rsid).toBe('rs662');
    });

    it('returns undefined for non-existent rsid', () => {
      const result = findSNP(snps, 'rs9999999');

      expect(result).toBeUndefined();
    });

    it('returns undefined for empty input', () => {
      expect(findSNP([], 'rs1801133')).toBeUndefined();
    });
  });

  describe('getSNPsWithGenotype', () => {
    const snps: SNP[] = [
      { rsid: 'rs1', chromosome: '1', position: 100, genotype: 'AA' },
      { rsid: 'rs2', chromosome: '1', position: 200, genotype: 'GG' },
      { rsid: 'rs3', chromosome: '1', position: 300, genotype: 'AA' },
      { rsid: 'rs4', chromosome: '1', position: 400, genotype: 'AG' },
      { rsid: 'rs5', chromosome: '1', position: 500, genotype: 'GG' },
    ];

    it('filters SNPs by genotype', () => {
      const result = getSNPsWithGenotype(snps, 'AA');

      expect(result).toHaveLength(2);
      expect(result.map(s => s.rsid)).toEqual(['rs1', 'rs3']);
    });

    it('returns all matching SNPs', () => {
      const result = getSNPsWithGenotype(snps, 'GG');

      expect(result).toHaveLength(2);
      expect(result.map(s => s.rsid)).toEqual(['rs2', 'rs5']);
    });

    it('returns empty array when no SNPs match genotype', () => {
      const result = getSNPsWithGenotype(snps, 'TT');

      expect(result).toHaveLength(0);
    });

    it('returns empty array for empty input', () => {
      expect(getSNPsWithGenotype([], 'AA')).toHaveLength(0);
    });

    it('requires exact genotype match', () => {
      const result = getSNPsWithGenotype(snps, 'AG');

      expect(result).toHaveLength(1);
      expect(result[0].rsid).toBe('rs4');
    });
  });

  describe('validateGenomeData', () => {
    it('validates data with sufficient SNPs and expected rsids', () => {
      const snps = generateLargeSNPSet(100000);
      // Add expected SNPs
      snps.push(
        { rsid: 'rs1801133', chromosome: '1', position: 11856378, genotype: 'GG' },
        { rsid: 'rs662', chromosome: '1', position: 230845699, genotype: 'AG' },
        { rsid: 'rs1799983', chromosome: '7', position: 150696111, genotype: 'TT' }
      );

      const result = validateGenomeData(snps as SNP[]);

      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('fails validation for empty SNP array', () => {
      const result = validateGenomeData([]);

      expect(result.valid).toBe(false);
      expect(result.errors).toContain('No valid SNPs found in the file');
    });

    it('warns about low SNP count', () => {
      const snps: SNP[] = [
        { rsid: 'rs1801133', chromosome: '1', position: 11856378, genotype: 'GG' },
        { rsid: 'rs662', chromosome: '1', position: 230845699, genotype: 'AG' },
        { rsid: 'rs1799983', chromosome: '7', position: 150696111, genotype: 'TT' },
      ];

      const result = validateGenomeData(snps);

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('Low SNP count'))).toBe(true);
    });

    it('warns about missing expected SNPs', () => {
      const snps = generateLargeSNPSet(100000);

      const result = validateGenomeData(snps as SNP[]);

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('Could not identify common SNPs'))).toBe(true);
    });

    it('passes validation if at least one expected SNP is found', () => {
      const snps = generateLargeSNPSet(100000);
      snps.push({ rsid: 'rs1801133', chromosome: '1', position: 11856378, genotype: 'GG' });

      const result = validateGenomeData(snps as SNP[]);

      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('reports multiple validation errors', () => {
      const result = validateGenomeData([]);

      expect(result.valid).toBe(false);
      expect(result.errors.length).toBeGreaterThanOrEqual(1);
    });
  });

  describe('getGenomeStats', () => {
    it('calculates statistics for empty array', () => {
      const stats = getGenomeStats([]);

      expect(stats.totalSNPs).toBe(0);
      expect(stats.uniqueChromosomes).toBe(0);
      expect(stats.chromosomeCounts).toEqual({});
      expect(stats.genotypeCounts).toEqual({});
    });

    it('calculates chromosome counts', () => {
      const snps: SNP[] = [
        { rsid: 'rs1', chromosome: '1', position: 100, genotype: 'AA' },
        { rsid: 'rs2', chromosome: '1', position: 200, genotype: 'GG' },
        { rsid: 'rs3', chromosome: '2', position: 100, genotype: 'CC' },
        { rsid: 'rs4', chromosome: 'X', position: 100, genotype: 'TT' },
      ];

      const stats = getGenomeStats(snps);

      expect(stats.totalSNPs).toBe(4);
      expect(stats.uniqueChromosomes).toBe(3);
      expect(stats.chromosomeCounts['1']).toBe(2);
      expect(stats.chromosomeCounts['2']).toBe(1);
      expect(stats.chromosomeCounts['X']).toBe(1);
    });

    it('calculates genotype counts', () => {
      const snps: SNP[] = [
        { rsid: 'rs1', chromosome: '1', position: 100, genotype: 'AA' },
        { rsid: 'rs2', chromosome: '1', position: 200, genotype: 'AA' },
        { rsid: 'rs3', chromosome: '1', position: 300, genotype: 'GG' },
        { rsid: 'rs4', chromosome: '1', position: 400, genotype: 'GG' },
        { rsid: 'rs5', chromosome: '1', position: 500, genotype: 'GG' },
      ];

      const stats = getGenomeStats(snps);

      expect(stats.genotypeCounts['AA']).toBe(2);
      expect(stats.genotypeCounts['GG']).toBe(3);
    });

    it('handles many chromosomes', () => {
      const snps: SNP[] = [];
      for (let i = 1; i <= 22; i++) {
        snps.push({ rsid: `rs${i}`, chromosome: String(i), position: i * 100, genotype: 'AA' });
      }
      snps.push({ rsid: 'rsX', chromosome: 'X', position: 100, genotype: 'GG' });
      snps.push({ rsid: 'rsY', chromosome: 'Y', position: 100, genotype: 'CC' });
      snps.push({ rsid: 'rsMT', chromosome: 'MT', position: 100, genotype: 'TT' });

      const stats = getGenomeStats(snps);

      expect(stats.totalSNPs).toBe(25);
      expect(stats.uniqueChromosomes).toBe(25);
    });

    it('handles various genotype formats', () => {
      const snps: SNP[] = [
        { rsid: 'rs1', chromosome: '1', position: 100, genotype: 'AA' },
        { rsid: 'rs2', chromosome: '1', position: 200, genotype: 'AT' },
        { rsid: 'rs3', chromosome: '1', position: 300, genotype: '--' },
        { rsid: 'rs4', chromosome: '1', position: 400, genotype: '' },
        { rsid: 'rs5', chromosome: '1', position: 500, genotype: 'II' },
        { rsid: 'rs6', chromosome: '1', position: 600, genotype: 'DD' },
      ];

      const stats = getGenomeStats(snps);

      expect(stats.totalSNPs).toBe(6);
      expect(stats.genotypeCounts['AA']).toBe(1);
      expect(stats.genotypeCounts['AT']).toBe(1);
      expect(stats.genotypeCounts['--']).toBe(1);
      expect(stats.genotypeCounts['']).toBe(1);
      expect(stats.genotypeCounts['II']).toBe(1);
      expect(stats.genotypeCounts['DD']).toBe(1);
    });
  });

  describe('edge cases and error handling', () => {
    it('handles very large position numbers', () => {
      const content = `rs1234567\t1\t999999999\tAA`;
      const result = parseGeneticData(content);

      expect(result.snps[0].position).toBe(999999999);
    });

    it('handles positions at chromosome boundaries', () => {
      const content = [
        'rs1\t1\t1\tAA',
        'rs2\t1\t9999999999\tGG',
      ].join('\n');
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(2);
    });

    it('handles extra whitespace in data', () => {
      const content = 'rs1801133  \t  1  \t  11856378  \t  GG  ';
      const result = parseGeneticData(content);

      expect(result.snps[0].rsid).toBe('rs1801133');
      expect(result.snps[0].chromosome).toBe('1');
      expect(result.snps[0].genotype).toBe('GG');
    });

    it('handles mixed line endings', () => {
      const content = 'rs1\t1\t100\tAA\r\nrs2\t1\t200\tGG\nrs3\t1\t300\tCC';
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(3);
    });

    it('handles duplicate SNPs', () => {
      const content = [
        'rs123\t1\t100\tAA',
        'rs123\t1\t100\tAA',
      ].join('\n');
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(2);
    });

    it('handles Windows-style line endings in AncestryDNA', () => {
      const content = 'rs1,1,100,A,A\r\nrs2,1,200,G,G';
      const result = parseGeneticData(content);

      expect(result.snps).toHaveLength(2);
      expect(result.snps[0].genotype).toBe('AA');
    });
  });
});
